### PR TITLE
[RFR] gh-action workflows

### LINKED ISSUE #2: resolve the wheel poisoning
the interaction of not having a python3 wheel and also not requiring a recent setuptools broke the build for many

### LINKED ISSUE #11: Move CI to github action
1. fix testing env tox
2. update pre-commit with latest hooks
3. workflows test-suite and deployment

### PR DESCRIPTION
**Pull request by digitronik**
part-3: #11 

FIXES #11 
FIXES #2

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
Lovely, needs a update for the others merges

**Comment by digitronik** [comment]
Moving to WIP. I need to debug why on runner i'm facing timeout issue for wharf `accepts_requests`. Locally all test passing.

**Comment by digitronik** [comment]
@RonnyPfannschmidt now PR ready for suggestions

workflow run: https://github.com/digitronik/webdriver_kaifuku/actions/runs/111393461
codecov: https://codecov.io/gh/digitronik/webdriver_kaifuku/branch/gh_action

**Review by RonnyPfannschmidt — APPROVED** [review]
lovely, thanks

**Pull request merged**
